[package]
name = "pit2sid"
version = "0.1.0"
authors = ["Tibor Nagy <xnagytibor@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
gba-compression = { git = "https://github.com/xtibor/gba-compression.git" }
