[package]
name = "tools"
version = "0.1.0"
authors = ["Tibor Nagy <xnagytibor@gmail.com>"]
edition = "2018"

[dependencies]
gba-compression = { git = "https://github.com/xtibor/gba-compression.git" }
image = "0.21"
structopt = "0.2"
